### PR TITLE
Codestyle improvements

### PR DESCRIPTION
**Pull request by BenchR267**
Thanks for your work! This are just some improvements of the codestyle :)

### CODE REVIEW

**Comment by BenchR267** [comment]
Ok, that does make sense. But why do you even need this property to be weak?

**Comment by gtsifrikas** [comment]
In this case it could not be weak and work just fine, i'm just following a tactic that i want every view to be owned only by the view hierarchy so if it is out the screen for some reason not to have allocated memory because i'm pointing strongly to it. Although i'm not sure of the validity of this practice now that i'm thinking about it.

**Comment by BenchR267** [comment]
Yeah, I think it's totally fine to keep that. That's also the way IBOutlets work, so it's definitely not wrong :) If you want me to change that, I'll do it today :)

**Comment by gtsifrikas** [comment]
Ok change it, and i'll merge it

**Comment by BenchR267** [comment]
Done! :+1:

**Pull request merged**
